name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            name: ccline-yescc-linux-x64.tar.gz
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: ccline-yescc-linux-x64-static.tar.gz
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
            name: ccline-yescc-windows-x64.zip
          - target: x86_64-apple-darwin
            os: macos-latest
            name: ccline-yescc-macos-x64.tar.gz
          - target: aarch64-apple-darwin
            os: macos-latest
            name: ccline-yescc-macos-arm64.tar.gz

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation tools
      if: matrix.target == 'x86_64-pc-windows-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Install musl tools
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools

    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Package Linux/macOS
      if: matrix.os != 'windows-latest' && matrix.target != 'x86_64-pc-windows-gnu'
      run: |
        mkdir -p dist
        cp target/${{ matrix.target }}/release/ccline-yescc dist/ccline-yescc
        cd dist
        tar czf ../${{ matrix.name }} ccline-yescc

    - name: Package Windows
      if: matrix.target == 'x86_64-pc-windows-gnu'
      run: |
        mkdir -p dist
        cp target/${{ matrix.target }}/release/ccline-yescc.exe dist/ccline-yescc.exe
        cd dist
        zip ../${{ matrix.name }} ccline-yescc.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.name }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*/*
        generate_release_notes: true
        draft: false
        prerelease: false

    - name: Setup Node.js for NPM
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Extract binaries from archives
      run: |
        mkdir -p extracted
        
        # macOS x64
        tar -xzf artifacts/ccline-yescc-macos-x64.tar.gz/ccline-yescc-macos-x64.tar.gz -C extracted
        mv extracted/ccline-yescc extracted/ccline-yescc-darwin-x64
        
        # macOS ARM64
        tar -xzf artifacts/ccline-yescc-macos-arm64.tar.gz/ccline-yescc-macos-arm64.tar.gz -C extracted
        mv extracted/ccline-yescc extracted/ccline-yescc-darwin-arm64
        
        # Linux x64
        tar -xzf artifacts/ccline-yescc-linux-x64.tar.gz/ccline-yescc-linux-x64.tar.gz -C extracted
        mv extracted/ccline-yescc extracted/ccline-yescc-linux-x64
        
        # Linux musl (static)
        tar -xzf artifacts/ccline-yescc-linux-x64-static.tar.gz/ccline-yescc-linux-x64-static.tar.gz -C extracted
        mv extracted/ccline-yescc extracted/ccline-yescc-linux-x64-musl
        
        # Windows
        unzip artifacts/ccline-yescc-windows-x64.zip/ccline-yescc-windows-x64.zip -d extracted
        mv extracted/ccline-yescc.exe extracted/ccline-yescc-win32-x64.exe
        
        # List extracted files
        ls -la extracted/

    - name: Prepare NPM packages
      run: |
        # Prepare packages with version management
        node npm/scripts/prepare-packages.js

        # Copy binaries to platform directories
        cp extracted/ccline-yescc-darwin-x64 npm-publish/darwin-x64/ccline-yescc
        cp extracted/ccline-yescc-darwin-arm64 npm-publish/darwin-arm64/ccline-yescc
        cp extracted/ccline-yescc-linux-x64 npm-publish/linux-x64/ccline-yescc
        cp extracted/ccline-yescc-linux-x64-musl npm-publish/linux-x64-musl/ccline-yescc
        cp extracted/ccline-yescc-win32-x64.exe npm-publish/win32-x64/ccline-yescc.exe

        # Set executable permissions for Unix binaries
        chmod +x npm-publish/darwin-x64/ccline-yescc
        chmod +x npm-publish/darwin-arm64/ccline-yescc
        chmod +x npm-publish/linux-x64/ccline-yescc
        chmod +x npm-publish/linux-x64-musl/ccline-yescc

        # Verify packages
        echo "Package structure:"
        find npm-publish -name "package.json" -exec echo "=== {} ===" \; -exec head -5 {} \;

    - name: Publish platform packages to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        # Publish platform packages first
        for platform in darwin-x64 darwin-arm64 linux-x64 linux-x64-musl win32-x64; do
          echo "📦 Publishing @hobeeliu/ccline-yescc-$platform"
          cd npm-publish/$platform
          npm publish --access public
          cd ../..
          echo "✅ Published @hobeeliu/ccline-yescc-$platform"
        done

    - name: Wait for NPM registry
      run: |
        echo "⏳ Waiting for platform packages to be available on NPM..."
        sleep 30

    - name: Publish main package to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd npm-publish/main
        echo "📦 Publishing @hobeeliu/ccline-yescc"
        npm publish --access public
        echo "✅ Published @hobeeliu/ccline-yescc"
        echo ""
        echo "🎉 NPM packages published successfully!"
        echo "Install with: npm install -g @hobeeliu/ccline-yescc"